---
    ###########################
    # Setup Kubernetes Cluster
    ###########################

- hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: delete-cluster
    tags: delete-cluster