apiVersion: apps/v1
kind: Deployment
metadata:
  name: csye7374-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: csye7374-operator
  template:
    metadata:
      labels:
        name: csye7374-operator
    spec:
      serviceAccountName: csye7374-operator
      containers:
        - name: csye7374-operator
          # Replace this with the built image name
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - csye7374-operator
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csye7374-operator"
