---
# tasks file for create-eks-cluster
- name: Gathering Zones
  aws_az_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: us-east-1
  register: zones1

- name: Debug
  set_fact:
    zones: "{{ zones1.availability_zones | map(attribute='zone_name') | join(',') }}"
 # register: "{{ msg.stdout }}"

- name: Create EKS cluster
  aws_eks_cluster:
    name: "{{ cluster_name }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ aws_region }}"
    state: present

