---
- name: Terminate EC2 instances
  vars_files:
    - external_vars.yml  #connection: local
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    aws_region: "us-east-1"
    ec2_tags:
      key: app
      value: web
      
  tasks:
    - name: Find EC2 Facts
      ec2_remote_facts:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ aws_region }}"
      register: ec2_facts

      # (-) is used to stip white spaces
      # http://jinja.pocoo.org/docs/dev/templates/#whitespace-control
    - name: Filter EC2 instances
      set_fact:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"

        #        ec2_instances: |
        #  {% set instances = [] %}
        #  {% for item in ec2_facts.instances if item.tags == ec2_tags and item.state == 'running' -%}
        #    {{ instances.append(item.id) }}
        #  {%- endfor %}
        #  {{ instances }}
    - name: Terminate EC2 server
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ aws_region }}"
        instance_ids: "{{ item }}"
        state: 'absent'
      with_items: "{{ ec2_facts.instances }}"
